# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'NIOSMTP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NIOSMTP
  pod 'SwiftNIO', '~> 2.0'
  pod 'SwiftNIOTransportServices', '~> 1.0'
  pod 'SwiftNIOExtras', '~> 1.0'

end
